# .github/workflows/ci.yml

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use a specific Node.js version, like 18 or 20

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test
        env:
          # Dummy environment variables for tests
          # The values don't matter since the tests mock the API calls
          GEMINI_API_KEY: "dummy_key"
          MONGODB_URI: "mongodb://dummy_uri"
